import { Project } from '../types';

export const projects: Project[] = [
    {
        id: 'project-1',
        title: 'Notifications',
        description: 'projects.notifications.description',
        image: 'https://res.cloudinary.com/dhvbp84vj/image/upload/v1758912681/notification_api_wp8n6n.png',
        technologies: ['Docker', 'Docker Compose', 'MongoDB', 'NestJS', 'TypeScript', 'Mongoose', 'Nodemailer', 'Swagger', 'Redis'],
        githubUrl: 'https://github.com/Scerutti/notifications',
        liveUrl: 'https://notifications-gipk.onrender.com/api',
        featured: true,
    },
    {
        id: 'project-2',
        title: 'Portfolio',
        description: 'projects.portfolio.description',
        image: 'https://res.cloudinary.com/dhvbp84vj/image/upload/v1758912681/portfolio_home_huxiel.png',
        technologies: ['React', 'TypeScript', 'Vite', 'TailwindCSS', 'Framer Motion', 'React Icons', 'Axios', 'ESLint'],
        githubUrl: 'https://github.com/Scerutti/portfolio-ref',
        liveUrl: 'https://portfolio-ref.vercel.app',
        featured: true,
    },
    {
        id: 'project-3',
        title: 'Funciones Básicas',
        description: 'projects.funciones.description',
        image: 'https://res.cloudinary.com/dhvbp84vj/image/upload/v1758912681/funciones_basicas_e2ycav.png',
        technologies: ['TypeScript', 'React', 'NPM'],
        githubUrl: '',
        liveUrl: 'https://www.npmjs.com/package/funciones-basicas',
        featured: true,
    },
    {
        id: 'project-4',
        title: 'Baires Hospedajes',
        description: 'projects.baires.description',
        image: 'https://res.cloudinary.com/dhvbp84vj/image/upload/v1758912681/baires_home_lulkf4.png',
        technologies: ['React', 'Next.js', 'TailwindCSS', 'NestJS', 'TypeScript', 'MongoDB', 'Leaflet', 'Firebase'],
        githubUrl: '',
        liveUrl: 'https://www.baireshospedajes.com.ar',
        featured: true,
    },
    {
        id: 'project-5',
        title: 'CRUD Personas - Servlets & JSP',
        description: 'projects.crud.description',
        image: 'https://res.cloudinary.com/dhvbp84vj/image/upload/v1758912681/portfolio_home_huxiel.png',
        technologies: ['Java', 'Servlets', 'JSP', 'Tomcat', 'MySQL', 'Logger'],
        githubUrl: 'https://github.com/Scerutti/servlet-java',
        liveUrl: '',
        featured: false,
    },
    {
        id: 'project-6',
        title: 'Geolocalización & Mapa Interactivo',
        description: 'projects.geolocation.description',
        image: 'https://res.cloudinary.com/dhvbp84vj/image/upload/v1758912681/portfolio_home_huxiel.png',
        technologies: ['React', 'TypeScript', 'Leaflet', 'React-Leaflet', 'Vite', 'Geolocation API'],
        githubUrl: 'https://github.com/Scerutti/geolocalizacion_nativajs_y_mapa_interactivo',
        liveUrl: '',
        featured: false,
    },
    {
        id: 'project-7',
        title: 'Taller Invitation Form',
        description: 'projects.taller.description',
        image: 'https://res.cloudinary.com/dhvbp84vj/image/upload/v1758912681/portfolio_home_huxiel.png',
        technologies: ['React', 'TypeScript', 'Material-UI', 'CSS', 'WhatsApp API'],
        githubUrl: 'https://github.com/Scerutti/taller-invitation-form',
        liveUrl: '',
        featured: false,
    },
    {
        id: 'project-8',
        title: 'Chuck Norris Jokes',
        description: 'projects.chuck.description',
        image: 'https://res.cloudinary.com/dhvbp84vj/image/upload/v1758912681/portfolio_home_huxiel.png',
        technologies: ['React', 'TypeScript', 'Material-UI', 'SweetAlert2', 'Vite', 'API Integration'],
        githubUrl: 'https://github.com/Scerutti/chuck-norris-jokes',
        liveUrl: 'https://chuck-norris-jokes-zeta.vercel.app',
        featured: false,
    },
];

